# Generated by Django 4.0.2 on 2022-03-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição')),
                ('natureza', models.CharField(choices=[('FISICO_QUIMICO', 'FÍSICO-QUÍMICO'), ('FITOPLANCTONS', 'FITOPLANCTONS'), ('ZOOPLANCTONS', 'ZOOPLANCTONS'), ('ANALISE_QUIMICA', 'ANÁLISE-QUÍMICA'), ('ANALISE_CLINICA', 'ANÁLISE-CLÍNICA'), ('FISIOLOGIA', 'FISIOLOGIA'), ('ANALISE_PRESUNTIVA', 'ANÁLISE-PRESUNTIVA'), ('BACTERIOLOGIA', 'BACTERIOLOGIA')], max_length=20, verbose_name='Natureza')),
                ('un_medida', models.CharField(choices=[('CEL_ML', 'cel/ml'), ('CENTIMETROS', 'Centímetros'), ('DOSE', 'Dose'), ('GRAMAS', 'Gramas'), ('GRAUS', 'Graus Celsios'), ('HECTARE', 'Hectare'), ('LIBRA', 'Libra'), ('METRO_CUBICO', 'Metro Cúbico'), ('METRO', 'Metro Quadrado'), ('METROS', 'Metros'), ('MG_L', 'mg/l'), ('MILILITRO', 'Mililitro'), ('PERCENTUAL', 'Percentual'), ('PPM', 'ppm'), ('PPT', 'ppt'), ('QUILOS', 'Quilos'), ('SEGUNDOS', 'Segundos'), ('TONELADA', 'Tonelada'), ('UFC_ML', 'UFC/ml')], max_length=12, verbose_name='Unidade de Medida')),
                ('permitido_min', models.IntegerField(verbose_name='Permitido Min.')),
                ('permitido_max', models.IntegerField(verbose_name='Permitido Max.')),
                ('ideal_max', models.IntegerField(verbose_name='Ideal Max.')),
                ('ativo', models.BooleanField(max_length=1, verbose_name='Ativo')),
            ],
        ),
    ]
