# Generated by Django 4.0.2 on 2022-03-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viveiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('BERCARIO', 'Berçário'), ('CANAL', 'Canal'), ('FINAL', 'Final/Engorda'), ('INTERMEDIARIO', 'Intermediário'), ('REPRODUTOR', 'Reprodutor'), ('SETOR', 'Setor')], max_length=13, verbose_name='Tipo')),
                ('area', models.CharField(max_length=15, verbose_name='Área')),
                ('un_medida', models.CharField(choices=[('CEL_ML', 'cel/ml'), ('CENTIMETROS', 'Centímetros'), ('DOSE', 'Dose'), ('GRAMAS', 'Gramas'), ('GRAUS', 'Graus Celsios'), ('HECTARE', 'Hectare'), ('LIBRA', 'Libra'), ('METRO_CUBICO', 'Metro Cúbico'), ('METRO', 'Metro Quadrado'), ('METROS', 'Metros'), ('MG_L', 'mg/l'), ('MILILITRO', 'Mililitro'), ('PERCENTUAL', 'Percentual'), ('PPM', 'ppm'), ('PPT', 'ppt'), ('QUILOS', 'Quilos'), ('SEGUNDOS', 'Segundos'), ('TONELADA', 'Tonelada'), ('UFC_ML', 'UFC/ml')], max_length=12, verbose_name='Unidade de Medida')),
                ('fator_densidade', models.CharField(max_length=8, verbose_name='Fator Densidade')),
                ('setor', models.CharField(max_length=20, verbose_name='Setor')),
                ('ciclo', models.CharField(max_length=15, verbose_name='Ciclo')),
                ('estado', models.CharField(max_length=15, verbose_name='Estado')),
                ('ativo', models.BooleanField(max_length=1, verbose_name='Ativo')),
            ],
        ),
    ]
