# Generated by Django 4.0.2 on 2022-03-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('tipo_plano_contas', models.CharField(choices=[('FIXO', 'FIXO'), ('VARIAVEL', 'VARIÁVEL')], max_length=8, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('custo_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Custo Médio (Compra, Consumo)')),
                ('ativo', models.BooleanField(max_length=1, verbose_name='Ativo')),
                ('plano_contas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_contas', to='financas.planoconta')),
            ],
        ),
    ]
