# Generated by Django 4.0.2 on 2022-03-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('fornecedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fornecedores.fornecedor')),
                ('data_nasc', models.DateField(blank=True, verbose_name='Data de Nascimento')),
            ],
            bases=('fornecedores.fornecedor',),
        ),
    ]
