# Generated by Django 4.0.2 on 2022-03-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('custo_un', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Custo Médio (R$) por Unid. de Consumo')),
                ('un_consumo', models.CharField(choices=[('CEL_ML', 'cel/ml'), ('CENTIMETROS', 'Centímetros'), ('DOSE', 'Dose'), ('GRAMAS', 'Gramas'), ('GRAUS', 'Graus Celsios'), ('HECTARE', 'Hectare'), ('LIBRA', 'Libra'), ('METRO_CUBICO', 'Metro Cúbico'), ('METRO', 'Metro Quadrado'), ('METROS', 'Metros'), ('MG_L', 'mg/l'), ('MILILITRO', 'Mililitro'), ('PERCENTUAL', 'Percentual'), ('PPM', 'ppm'), ('PPT', 'ppt'), ('QUILOS', 'Quilos'), ('SEGUNDOS', 'Segundos'), ('TONELADA', 'Tonelada'), ('UFC_ML', 'UFC/ml')], max_length=15, verbose_name='Unidade de Consumo')),
                ('categoria', models.CharField(choices=[('PESTICIDAS', 'Pesticidas'), ('INSUMO_CUSTO_INICIAL', 'Insumo/Custo Inicial'), ('RACAO', 'Ração'), ('VITAMINAS', 'Vitaminas')], max_length=25, verbose_name='Categoria')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('classificacao', models.CharField(choices=[('FINAL', 'Final (Acabamento)'), ('INICIAL', 'Inicial'), ('INTERMEDIARIA', 'Intermediária'), ('NENHUMA', 'Nenhuma')], max_length=20, verbose_name='Classificação')),
                ('validade', models.DateField(blank=True, verbose_name='Validade')),
                ('peso_embalagem', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Peso Embalagem')),
                ('embalagem', models.CharField(blank=True, choices=[('BALDE', 'Balde'), ('CAIXA', 'Caixa'), ('FRASCO', 'Frasco'), ('LATA', 'Lata'), ('SACO', 'Saco'), ('NENHUMA', 'Nenhuma')], max_length=20, verbose_name='Embalagem')),
                ('ativo', models.BooleanField(max_length=1, verbose_name='Ativo')),
                ('controla_estoque', models.BooleanField(max_length=1, verbose_name='Controla Estoque')),
                ('permite_negativo', models.BooleanField(max_length=1, verbose_name='Permite Negativo')),
                ('fornecedor', models.ManyToManyField(blank=True, related_name='fornecedor', to='fornecedores.Fornecedor')),
            ],
        ),
    ]
