# Generated by Django 4.0.2 on 2022-03-29 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='insumo',
            name='fornecedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor', to='fornecedores.fornecedor'),
            preserve_default=False,
        ),
    ]
