# Generated by Django 4.0.2 on 2022-03-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cnpj_cpf', models.CharField(max_length=20, unique=True, verbose_name='CNPJ/CPF')),
                ('tipo_pessoa', models.CharField(choices=[('FISICA', 'Física'), ('JURIDICA', 'Jurídica')], max_length=8, verbose_name='Tipo de Pessoa')),
                ('ie_rg', models.CharField(blank=True, max_length=20, verbose_name='IE/RG')),
                ('tipo_parceiro', models.CharField(choices=[('CLIENTE_EXTERNO', 'Cliente Externo'), ('CLIENTE_INTERNO_FRIGORIFICO', 'Cliente Interno/Frigorífico'), ('CLIENTE_BENEFICIAMENTO', 'Cliente Beneficiamento'), ('FORNECEDOR_MATERIA_PRIMA', 'Fornecedor de Matéria Prima'), ('FORNECEDOR_INSUMOS', 'Fornecedor de Insumos'), ('LABORATORIO_LARVICULTURA', 'Laboratório / Larvicultura'), ('PRESTADOR_SERVICO', 'Prestador de Serviço'), ('FUNCIONARIO', 'Funcionário')], max_length=30, verbose_name='Tipo de Fornecedor')),
                ('logradouro', models.CharField(blank=True, max_length=100, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=20, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=20, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('EX', 'EX'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsável')),
                ('contato', models.CharField(max_length=15, verbose_name='Contato')),
                ('email', models.EmailField(blank=True, max_length=75, verbose_name='E-mail')),
            ],
        ),
    ]
